feature/show person details
wroblewski82/movies-browser pull request #20
Opened 2024-06-24 19:13 UTC by wroblewski82

I have implemented a dynamic Actor Details Page that updates in real-time when a user clicks on an actor's tile. Upon clicking, the page retrieves detailed information about the actor from the API using their ID. This includes information such as the actor's date and place of birth, as well as their biography. The page also displays a list of movies in which the actor has participated.

2024-06-25 21:14 UTC, sofyahreksoftware requested changes
Good job! As always, I have a few tips:)

- I think there is no point in adding a MovieList component with styles in the PeopleDetails folder. We already have a MovieList component with its styles and HTML skeleton as a separate feature, and we also have a styled.js file in features with styled lists. You can use styles imported directly from there.

-Additionally, it would be better if you rename `**PeopleDetailsSaga**` and `**PeopleDetailsSlice**` to `**PersonDetailsSaga**` and `**PersonDetailsSlice**` because in this situation we manage information about one person. Furthermore, we should decide on one name: Actor or Person. I think `*Person*` would be better because we represent information not only about actors but also directors, cast, and crew, etc.

- It's better to rename ActorProfile component to **PersonPage** for consistency with the remaining features' names of the App. And also change names of related names (actor to person):

I have also left some notes in comments directly in code, so bring attention to them:)

Congratulation! It was a good job and and good contribution to the development of the application🤪😍

2024-06-25 21:14 UTC, sofyahreksoftware commented on src/common/ImagePlaceholder/styled.js
> +      @media (max-width: ${({ theme }) => theme.media.mobile}px) {
It's better to add a blank line here for better readability.

2024-06-25 21:14 UTC, sofyahreksoftware commented on src/features/PeopleDetails/ActorProfile/styled.js
> +export const StyledDiv = styled.div`
I think StyledDiv isn't a good name:) What do you think about naming it as something like`**DataContainer**`?🤔

2024-06-25 21:14 UTC, sofyahreksoftware commented on src/features/PeopleDetails/MoviesList/index.js
> +          </StyledItem>
What do you think about adding `*?*` operator before methods as _toFixed/map_ etc. This will avoid potential errors:)

2024-06-29 19:45 UTC, wroblewski82 commented on src/features/PeopleDetails/MoviesList/index.js
> +          </StyledItem>
I think it's a good idea.

2024-06-29 20:17 UTC, wroblewski82 commented
Hi Sofia!
Thanks for your feedback. Here are the changes I made:

1. Styling the MoviesList component:
I moved the StyledHeader to the general styles, using props and changing the tag. This should improve style consistency.

2. Names PeopleDetailsSaga, PeopleDetailsSlice, and PeopleDetails:
I kept these names because they refer to multiple people, not single cases. This makes the code more intuitive.

3. Distinction between people and person:
In some places, I used "people" and in others "person" to better differentiate the context of these names.

4. Changing ActorProfile to PersonPage:
I changed the name ActorProfile to PersonPage, which better reflects the content of the page.

5. Minor adjustments:
I made a few minor adjustments to improve the functionality and readability of the code.

I believe these changes are reasonable, and the code can stay in this form.
Thanks for your work and suggestions!

Best regards,
Radek

2024-06-30 12:16 UTC, sofyahreksoftware approved these changes
Now it looks better.
There is also a small change you can make.
Before all the attributes in the MovieList and PersonPage files, you can add a dollar sign ($) so that the code is consistent with the latest practices. You can read more about it in the React documentation here.
https://styled-components.com/docs/api#transient-props

2024-07-01 18:54 UTC, merged