NavigationBar
wroblewski82/movies-browser pull request #5
Opened 2024-05-15 19:31 UTC by dawidkasza

2024-05-17 01:46 UTC, wroblewski82 commented
Great job.
The main problem I noticed is that the page layout breaks down on a smaller screen width.
Additionally, the styling of the components could be reduced a bit in some places.

2024-05-18 10:48 UTC, sofyahreksoftware requested changes
Great job, just a few things!! 🤗

2024-05-18 10:48 UTC, sofyahreksoftware commented on src/App.js
> +        </Switch>
I suggest we refactor the routing configuration as shown above.
By switching from to and using element instead of component, we align our code with the latest best practices of React Router. This adjustment simplifies our code and prevents unnecessary re-renders according to the last version of documentation of the React Router.
Additionally, using <Route exact path="/" render={() => } /> ensures that redirects happen only when the URL exactly matches the root.

```js
<HashRouter>
  <Navigation />
  <Routes>
    <Route path="/movies" component={Movies} />
    <Route path="/people" component={People} />
    <Route exact path="/" render={() => <Redirect to="/movies" />} />
  </Routes>

2024-05-18 10:48 UTC, sofyahreksoftware commented on src/Navigation/Search/index.js
> +      <SearchForm />
Here should be a placeholder:)
```js
  <SearchForm placeholder="Search dor movies..." />

2024-05-18 10:48 UTC, sofyahreksoftware commented on src/globalStyles.js
> +  //word-break: break-word;
I think, it's better to remove this comment😎

2024-05-18 10:48 UTC, sofyahreksoftware commented on src/Pages/Movies/index.js
> +export default Movies;
I'd like to suggest *removing Movie component* from Navigation folder. It do not directly relate to navigation. In future, we will create *MovieList* feature instead.

2024-05-18 10:48 UTC, sofyahreksoftware commented on src/Pages/People/index.js
> +export default People;
I'd like to suggest *removing People component* from Navigation folder. It do not directly relate to navigation. In future, we will create *PeopleList* feature instead.

2024-05-22 18:57 UTC, wroblewski82 approved these changes
Good job, you can merge.

2024-05-22 19:02 UTC, merged